name: Pull request checks
on:
  project: 
    types: [closed]
  # milestone: 
  #   types: [closed]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Execute tests to calculate coverage
        run: yarn test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
